DSND-1874 Add new business logic to delete officer from primary search
companieshouse/search.api.ch.gov.uk pull request #185
Opened 2023-06-29 11:49 UTC by kinpang-CH

* Add new endpoint to OfficersSearchController
* Refactor service to be used for both disqualifications and officers
* Refactor request service to be used for both disqualifications and officers
* Refactor to focus context on primary search rather than disqualifications

Resolves [DSND-1874](https://companieshouse.atlassian.net/browse/DSND-1874)

2023-06-29 14:06 UTC, sthompsonCH approved these changes

2023-07-04 10:47 UTC, cgregoryCH requested changes

2023-07-04 10:59 UTC, kinpang-CH commented on src/main/java/uk/gov/companieshouse/search/api/service/delete/primary/PrimarySearchDeleteRequestService.java
> +    @Autowired
Addressed in latest commit.

2023-07-04 10:59 UTC, kinpang-CH commented on src/main/java/uk/gov/companieshouse/search/api/service/delete/primary/PrimarySearchDeleteService.java
> +    @Autowired
Addressed in latest commit.

2023-07-04 12:20 UTC, cgregoryCH approved these changes

2023-07-04 12:26 UTC, merged