DSND-1593 Implement PUT endpoint for officers primary search
companieshouse/search.api.ch.gov.uk pull request #187
Opened 2023-07-06 12:27 UTC by cgregoryCH

* Upserts officer appointments passed in as the request body to the primary search index in elastic search.
* Includes implementation of the DELETE endpoint also which was reviewed as part of [PR 185](https://github.com/companieshouse/search.api.ch.gov.uk/pull/185)

[DSND-1593](https://companieshouse.atlassian.net/browse/DSND-1593)

[DSND-1593]: https://companieshouse.atlassian.net/browse/DSND-1593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-07-06 14:00 UTC, sthompsonCH approved these changes

2023-07-06 17:02 UTC, johncook-ch approved these changes

2023-07-06 17:06 UTC, johncook-ch approved these changes

2023-07-07 06:02 UTC, hwilliams1 requested changes
Currently, this PR can never pass as the concourse pipeline is set to use Java 8 and this changes the version of Java to Java 11. One of these would need to change for this to be able to work.

2023-07-07 10:17 UTC, kinpang-CH approved these changes

2023-07-10 09:37 UTC, hwilliams1 approved these changes
As the pipeline now successfully builds and the sonar smells have been addressed, approving this.

2023-07-10 10:49 UTC, johncook-ch approved these changes

2023-07-10 10:50 UTC, merged